export enum CardFilter {
    NameContains = "name_contains",
    DescriptionContains = "description_contains",
    LevelUpContains = "level_up_contains",
    AttackEquals = "attack_equals",
    AttackGreater = "attack_greater",
    AttackLess = "attack_less",
    HealthEquals = "health_equals",
    HealthGreater = "health_greater",
    HealthLess = "health_less",
    CostEquals = "cost_equals",
    CostGreater = "cost_greater",
    CostLess = "cost_less",
    HasKeyword = "has_keyword",
    HasSupertype = "has_supertype",
    HasType = "has_type",
    HasSubtype = "has_subtype",
    FromRegion = "from_region",
    FromSet = "from_set",
    SpellSpeed = "spell_speed",
    HasRarity = "rarity"
}